services:
  scaytrase.theme_registry:
    class:  ScayTrase\SwitchableThemeBundle\Service\ThemeRegistry
    tags:
    - {name: autoregistry, tag: theme }

  scaytrase.switchable_theme.theme_instance_type:
    class: ScayTrase\SwitchableThemeBundle\Form\Type\ThemeInstanceType
    arguments: [ @scaytrase.theme_registry ]
    tags:
    - { name: form.type, alias: switchable_theme_instance }
